SELECT * FROM TAB_IES
GO

SELECT TOP(10) * FROM TAB_REGISTRO
GO

SELECT TOP(100) NOME_CURSO_BOLSA, COD_EMEC_IES_BOLSA, TIPO_BOLSA
FROM TAB_REGISTRO
GO

SELECT TOP(100) NOME_CURSO_BOLSA AS 'NOME DO CURSO', COD_EMEC_IES_BOLSA AS 'CÓDIGO EMEC DA INSTITUIÇÃO', TIPO_BOLSA AS 'BOLSA OFERTADA'
FROM TAB_REGISTRO
GO

SELECT TOP(1000) NOME_CURSO_BOLSA, COD_EMEC_IES_BOLSA, TIPO_BOLSA
FROM TAB_REGISTRO
WHERE ANO_CONCESSAO_BOLSA = 2016
GO

SELECT TOP(1000) NOME_CURSO_BOLSA, COD_EMEC_IES_BOLSA, TIPO_BOLSA
FROM TAB_REGISTRO
WHERE COD_RACA = 2
GO

SELECT NOME_CURSO_BOLSA, COD_EMEC_IES_BOLSA, TIPO_BOLSA
FROM TAB_REGISTRO
WHERE ANO_CONCESSAO_BOLSA >= 2016 AND COD_RACA = 2 AND NOME_CURSO_BOLSA = 'Engenharia Civil'
GO

SELECT * FROM TAB_RACA
GO

-- BOLSAS CONCEDIDAS A HOMENS E MULHERES EM 2016

SELECT COUNT(SEXO_BENEFICIARIO_BOLSA) AS 'BOLSAS CONCEDIDAS A MULHERES (2016)' FROM TAB_REGISTRO	
WHERE SEXO_BENEFICIARIO_BOLSA = 'F' AND ANO_CONCESSAO_BOLSA = 2016
GO

SELECT COUNT(SEXO_BENEFICIARIO_BOLSA) AS 'BOLSAS CONCEDIDAS A HOMENS (2016)' FROM TAB_REGISTRO	
WHERE SEXO_BENEFICIARIO_BOLSA = 'M' AND ANO_CONCESSAO_BOLSA = 2016
GO