SELECT DISTINCT ANO_CONCESSAO_BOLSA AS ANO
FROM TAB_REGISTRO

SELECT DISTINCT NOME_CURSO_BOLSA AS CURSOS
FROM TAB_REGISTRO


SELECT DISTINCT TIPO_BOLSA
FROM TAB_REGISTRO

SELECT DISTINCT SEXO_BENEFICIARIO_BOLSA AS SEXO
FROM TAB_REGISTRO

SELECT DISTINCT MODALIDADE_ENSINO_BOLSA AS MODALIDADE
FROM TAB_REGISTRO

SELECT DISTINCT SIGLA_UF,
		CASE WHEN SIGLA_UF = 'AL' THEN 'Alagoas'
		WHEN SIGLA_UF = 'PB' THEN 'Paraiba'
		WHEN SIGLA_UF = 'PE' THEN 'Pernambuco'
		WHEN SIGLA_UF = 'RR' THEN 'Roraima'
		WHEN SIGLA_UF = 'GO' THEN 'Goias'
		WHEN SIGLA_UF = 'MS' THEN 'Mato Grosso do Sul'
		WHEN SIGLA_UF = 'DF' THEN 'Distrito Federal'
		WHEN SIGLA_UF = 'AP' THEN 'Amapa'
		WHEN SIGLA_UF = 'ES' THEN 'Espirito Santo'
		WHEN SIGLA_UF = 'PA' THEN 'Para'
		WHEN SIGLA_UF = 'RS' THEN 'Rio Grande do Sul'
		WHEN SIGLA_UF = 'SC' THEN 'Santa Catarina'
		WHEN SIGLA_UF = 'AM' THEN 'Amazonas'
		WHEN SIGLA_UF = 'AC' THEN 'Acre'
		WHEN SIGLA_UF = 'RO' THEN 'Rondonia'
		WHEN SIGLA_UF = 'MG' THEN 'Minas Gerais'
		WHEN SIGLA_UF = 'MT' THEN 'Mato Grosso'
		WHEN SIGLA_UF = 'RN' THEN 'Rio Grande do Norte'
		WHEN SIGLA_UF = 'BA' THEN 'Bahia'
		WHEN SIGLA_UF = 'PR' THEN 'Parana'
		WHEN SIGLA_UF = 'MA' THEN 'Maranhao'
		WHEN SIGLA_UF = 'SP' THEN 'Sao Paulo'
		WHEN SIGLA_UF = 'CE' THEN 'Ceara'
		WHEN SIGLA_UF = 'RJ' THEN 'Rio de Janeiro'
		WHEN SIGLA_UF = 'SE' THEN 'Sergipe'
		WHEN SIGLA_UF = 'PI' THEN 'Piaui'
		WHEN SIGLA_UF = 'TO' THEN 'Tocantins'
		ELSE 'Não Informado'
		END AS 'ESTADO'
FROM TAB_LOCAL

